# Generated by Django 4.1.4 on 2023-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_CGPA', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
    ]
